### ISSUE TITLE
The link "http://trials.dyanmics.com/" should be wrong for "Office 365 & Dynamics 365" in README.md

### ISSUE THREAD

**Issue by keijiinoue** [gregdegruy/customer-insights#11]
There should be a typo in the URL "http://trials.dyanmics.com/"

**Comment by gregdegruy** [comment]
Thanks @keijiinoue I have changed it to [https://trials.dynamics.com/](https://trials.dynamics.com/) under [this commit](https://github.com/gregdegruy/customer-insights/commit/1db8c48dc8f55e4b8f9965c79195a709da739402).
