### ISSUE TITLE
Customer Insights Full DataSource Creation thru C# API

### ISSUE THREAD

**Issue by erturkm** [gregdegruy/customer-insights#7]
I have tried retrieving datasources from one environment and pushed the same datasources to another environment by only changing the instanceId reference in the datasourcemetadata. 
However, since i was unable to specify the source and query of the data in metadata, in target environment datasources were created but never loaded and stuck at refreshing state. 

I have used below code piece to achieve it, 

using Microsoft.Customer360.Beta;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;

namespace CustomerInsightsConsole
{
    class Program
    {

        static readonly HttpClient httpClient = new HttpClient();

        public static void SerializeNow(ICollection<DataSourceInfo> datasources)
        {
                        
            Stream s = File.Open("cimodel.dat", FileMode.Create);
            BinaryFormatter b = new BinaryFormatter();
            b.Serialize(s, datasources);
            s.Close();
        }

        public static ICollection<DataSourceInfo> DeSerializeNow()
        {
            Stream s = File.Open("cimodel.dat", FileMode.Open);
            BinaryFormatter b = new BinaryFormatter();
            
            var result= (ICollection<DataSourceInfo>)b.Deserialize(s);
            s.Close();

            return result;
        }

        static void Main(string[] args)
        {
            //Console.WriteLine("Hello World!");

            string bearerToken = "";

            try
            {

                var customerInsights = new CustomerInsights(httpClient,bearerToken);
                //customerInsights.BaseUrl = "https://prod-weu-01.api.ci.ai.dynamics.com";

                InstanceMetadata instanceMetadata;
                var instanceId = new Guid("a42c6089-cf65-4a13-8e95-dabb53973a0c");

                //targetInstanceId
                var targetInstanceId = new Guid("aa530fe7-b12c-46a7-adb4-0e93d1b47772");

                instanceMetadata = customerInsights.GetInstanceAsync(instanceId, bearerToken).Result;
                Console.WriteLine("Instance id: " + instanceMetadata.InstanceId);
                Console.WriteLine("Instance name: " + instanceMetadata.Name);
                Console.WriteLine("Instance region: " + instanceMetadata.Region);
                Console.WriteLine("Instance tenant name: " + instanceMetadata.TenantName);

                var dataSources = customerInsights.GetAllDatasourceAsync(instanceId, bearerToken).Result;

                //SerializeNow(dataSources);

                //var resultReadFromFile = DeSerializeNow();

                   foreach (var item in dataSources)
                 {
                   item.DataSourceMetadata.InstanceId = targetInstanceId;

                 customerInsights.AddDatasourceAsync(targetInstanceId, item.DataSourceMetadata, bearerToken);

                }

                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine("Please paste a new bearer token");
                
                Console.ReadLine();
                
            }

        }
    }
}

**Comment by gregdegruy** [comment]
@erturkm There have been some major updates to the API to better support external use, previously this repo was built on the experimental internal swagger spec. Going forward the team's plan is to have this C# API built alongside the more stable external swagger spec. 

Unfortunately I may have to close this issue if okay with you until the external swagger spec and upcoming developer portal is in place in order to support this.
