### ISSUE TITLE
Customer Insights Metadata is not Serializable

### ISSUE THREAD

**Issue by erturkm** [gregdegruy/customer-insights#8]
I have tried using serialize functions of c# to serialize the datametadata i read from the Customer Insights, so that i can save the same as binary file and at a later stage read the datamodel from binary and import to another environment. 

However code fails with message "{"Type 'Microsoft.Customer360.Beta.DataSourceInfo' in Assembly 'CustomerInsights, Version=0.0.4.0, Culture=neutral, PublicKeyToken=d65bb566f29aab72' is not marked as serializable."}"

using Microsoft.Customer360.Beta;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;

namespace CustomerInsightsConsole
{
    class Program
    {

        static readonly HttpClient httpClient = new HttpClient();

        public static void SerializeNow(ICollection<DataSourceInfo> datasources)
        {
                        
            Stream s = File.Open("cimodel.dat", FileMode.Create);
            BinaryFormatter b = new BinaryFormatter();
            b.Serialize(s, datasources);
            s.Close();
        }

        public static ICollection<DataSourceInfo> DeSerializeNow()
        {
            Stream s = File.Open("cimodel.dat", FileMode.Open);
            BinaryFormatter b = new BinaryFormatter();
            
            var result= (ICollection<DataSourceInfo>)b.Deserialize(s);
            s.Close();

            return result;
        }

        static void Main(string[] args)
        {
            //Console.WriteLine("Hello World!");

            string bearerToken = "";

            try
            {

                var customerInsights = new CustomerInsights(httpClient,bearerToken);
                //customerInsights.BaseUrl = "https://prod-weu-01.api.ci.ai.dynamics.com";

                InstanceMetadata instanceMetadata;
                var instanceId = new Guid("a42c6089-cf65-4a13-8e95-dabb53973a0c");

                //targetInstanceId
                var targetInstanceId = new Guid("aa530fe7-b12c-46a7-adb4-0e93d1b47772");

                instanceMetadata = customerInsights.GetInstanceAsync(instanceId, bearerToken).Result;
                Console.WriteLine("Instance id: " + instanceMetadata.InstanceId);
                Console.WriteLine("Instance name: " + instanceMetadata.Name);
                Console.WriteLine("Instance region: " + instanceMetadata.Region);
                Console.WriteLine("Instance tenant name: " + instanceMetadata.TenantName);

                var dataSources = customerInsights.GetAllDatasourceAsync(instanceId, bearerToken).Result;

                SerializeNow(dataSources);

                var resultReadFromFile = DeSerializeNow();

                //   foreach (var item in dataSources)
                // {
                //   item.DataSourceMetadata.InstanceId = targetInstanceId;

                // customerInsights.AddDatasourceAsync(targetInstanceId, item.DataSourceMetadata, bearerToken);

                //}

                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine("Please paste a new bearer token");
                
                Console.ReadLine();
                
            }

        }
    }
}

**Comment by gregdegruy** [comment]
@erturkm this was resolved in the [0.0.10 release](https://www.nuget.org/packages/CustomerInsights/) of the API.
